[package]
name = "p2p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p2p_channel = {git = "https://github.com/vnt-dev/p2p_channel.git"}
ctrlc2 = "3.5"
#p2p_channel = {path = "./p2p_channel"}